name: Netbox
run-name: Netbox
permissions:
  id-token: write
  contents: read
  actions: read
on:
  push:
    branches:
      - "main"
    paths:
      - /apps/netbox/ptl/netbox.yaml
  workflow_dispatch:

jobs:
  netbox:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up kubelogin for non-interactive login
        uses: azure/use-kubelogin@v1
        with:
          kubelogin-version: 'v0.0.24'
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ae4401e2-f8e6-4bbd-9ced-f42c4dfaea70 
          tenant-id: 531ff96d-0ae9-462a-8d2d-bec7c0b42082 
          allow-no-subscriptions: true
      - uses: azure/aks-set-context@v3
        name: Get Aks context
        with:
          resource-group: 'ss-ptlsbox-00-rg'
          cluster-name: 'ss-ptlsbox-00-aks'
          subscription: DTS-SHAREDSERVICESPTL-SBOX
          #use-kubelogin: 'true'
      - name: echo a file
        run: cat ${{ env.KUBECONFIG }}
      - name: Setup kubectl
        id: install-kubectl
        uses: azure/setup-kubectl@v3
      - name: kubeversion
        run: kubectl version --client
      - uses: yokawasa/action-setup-kube-tools@v0.9.2
      - run: |
          kubectl version --client
          kubectl config get-context
          kubectl get ns
      - name: run command
        run: az aks command invoke --resource-group ss-ptlsbox-00-rg --name ss-ptlsbox-00-aks --command "kubectl config current-context"
      - name: run curl command
        id: getstatus
        run: az aks command invoke --resource-group ss-ptlsbox-00-rg --name ss-ptlsbox-00-aks --command "kubectl run mycurlpod --image=curlimages/curl --rm -i --tty -n netbox -- curl -s -o /dev/null -w \"%{http_code}\" netbox"
      - name: output
        run: echo ${{ steps.getstatus.outputs.* }}





#       - name: Delete test
#         id: delete_test
#         uses: kubeshop/testkube-docker-action@v1
#         with:
#           command: delete
#           resource: test
#           parameters: curl-test
#       - name: Deploy to AKS
#         id: deploy-aks
#         uses: Azure/k8s-deploy@v4
#         with:
#           namespace: 'default'
#           manifests: |
#             deploy.yaml
#       - uses: actions-hub/kubectl@master
#         with:
#           args: get ns
